import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "@/components/basic/ClientLayout";
import Header from "@/components/main/Header";
import Sidebar from "@/components/main/Sidebar";
import CurrentRoute from "@/components/main/CurrentRoute";

export const metadata: Metadata = {
    title: "미리내를 잇는 코드",
    description: "Tech Blog generated by SeHIgh",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body
                className="h-screen flex flex-col p-4 font-galmuri9 antialiased"
                suppressHydrationWarning={true}
            >
                <ClientLayout>
                    <div className="w-full h-full flex-1 flex flex-col">
                        <main className="dark:text-invert bg-gray-600 border-8 border-gray-600 rounded-t-xl overflow-auto flex flex-row justify-between gap-2 flex-1">
                            <Sidebar />
                            <section className="flex flex-col flex-1 gap-2 overflow-hidden">
                                <Header />
                                {/* Rendering 될 내용 */}
                                <div className="flex-1 bg-background border-4 border-border overflow-y-auto">
                                    {children}
                                </div>
                                <CurrentRoute />
                            </section>
                        </main>
                    </div>
                </ClientLayout>
            </body>
        </html>
    );
}
