import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "@/components/basic/ClientLayout";
import Header from "@/components/main/Header";
// import CurrentRoute from "@/components/main/CurrentRoute";
import { ThemeProvider } from "@/components/basic/themeProvider";
import ResponsiveSidebar from "@/components/main/Responsive";
import { cn } from "@/lib/utils";
import Footer from "@/components/main/Footer";

export const metadata: Metadata = {
    title: "미리내를 잇는 코드",
    description: "Tech Blog generated by SeHIgh",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko" suppressHydrationWarning>
            <body className="min-h-dvh max-h-dvh w-full flex flex-col justify-center p-1 font-galmuri9 antialiased overflow-x-hidden bg-background">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <ClientLayout>
                        {/* (임시) border-4 */}
                        <main className="w-full dark:text-invert bg-foreground border-4 border-foreground rounded-t-xl overflow-auto flex flex-row justify-between gap-1 flex-1">
                            <ResponsiveSidebar />
                            <section className="flex flex-col flex-1 gap-1 overflow-hidden">
                                <Header />
                                {/* Rendering 될 내용 */}
                                <div
                                    className={cn(
                                        "w-full flex-1 bg-background overflow-y-auto",
                                        // "border-4 border-border",
                                        "inset-ring-4 inset-ring-border"
                                    )}
                                >
                                    {children}
                                </div>
                                {/* <CurrentRoute /> */}
                                <Footer />
                            </section>
                        </main>
                    </ClientLayout>
                </ThemeProvider>
            </body>
        </html>
    );
}
