name: Java CICD
'on':
  push:
    branches:
     - v2
  workflow_dispatch: {
    }
x_name: 워크플로우 기본 설정
x_description: GitHub Actions 워크플로우 이름과 트리거 조건을 설정하는 블록입니다.
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps: [
      ]
